### ISSUE TITLE
Problems installing on OSX

### ISSUE THREAD

**Issue by tommypreger** [huffpostdata/node-lightnpng#1]
I'm having problems installing lightnpng on mac OSX 10.11.6.

Message: 
```
 CXX(target) Release/obj.target/lightnpng/src/init.o
In file included from ../src/init.cc:1:
../src/write_png.h:5:10: fatal error: 'cstdint' file not found
#include <cstdint>
```

How do I work around this?

**Comment by adamhooper** [comment]
Looks like https://stackoverflow.com/questions/10116724/clang-os-x-lion-cannot-find-cstdint has some ideas. I don't have Mac OS X so I can't test ... but I can attempt a fix anyway. It'll be tomorrow.

**Comment by adamhooper** [comment]
@tommypreger I've tried fixing it in v1.0.3. Could you please try reinstalling?

**Comment by tommypreger** [comment]
Hi Adam! Thanks for replying!

I tried installing again, but now I get another similar error message instead:

`
  CXX(target) Release/obj.target/lightnpng/src/init.o
  CXX(target) Release/obj.target/lightnpng/src/write_png.o
In file included from ../src/write_png.cc:3:
../src/compress.h:4:10: fatal error: 'forward_list' file not found
#include <forward_list>
`

**Comment by adamhooper** [comment]
Could you please try v1.0.4, which I just published?

`forward_list` must be a feature that's too new for OSX's old compiler. I changed it to `list`, which OSX _must_ know about....

**Comment by tommypreger** [comment]
Still having problems I'm afraid... Thanks for looking into this!
Now error reads:

```
  CXX(target) Release/obj.target/lightnpng/src/init.o
  CXX(target) Release/obj.target/lightnpng/src/write_png.o
../src/write_png.cc:49:30: error: no member named 'cbegin' in
      'std::list<std::basic_string<char>, std::allocator<std::basic_string<char>
      > >'
  for (auto it = chunks.data.cbegin(); it != chunks.data.cend(); ++it) {
                 ~~~~~~~~~~~ ^
../src/write_png.cc:49:58: error: no member named 'cend' in
      'std::list<std::basic_string<char>, std::allocator<std::basic_string<char>
      > >'
  for (auto it = chunks.data.cbegin(); it != chunks.data.cend(); ++it) {
                                             ~~~~~~~~~~~ ^
../src/write_png.cc:124:8: error: no member named 'unique_ptr' in namespace
      'std'
  std::unique_ptr<uint8_t[]> scanlines(new uint8_t[scanlines_len]);
  ~~~~~^
../src/write_png.cc:124:19: error: unexpected type name 'uint8_t': expected
      expression
  std::unique_ptr<uint8_t[]> scanlines(new uint8_t[scanlines_len]);
                  ^
../src/write_png.cc:124:27: error: expected expression
  std::unique_ptr<uint8_t[]> scanlines(new uint8_t[scanlines_len]);
                          ^
../src/write_png.cc:124:30: error: use of undeclared identifier 'scanlines'
  std::unique_ptr<uint8_t[]> scanlines(new uint8_t[scanlines_len]);
                             ^
../src/write_png.cc:125:38: error: use of undeclared identifier 'scanlines'
  native_argb32_to_scanlines(bytes, &scanlines[0], width, height, stride);
                                     ^
../src/write_png.cc:127:41: error: use of undeclared identifier 'scanlines'
  CompressResult zlibChunks = compress(&scanlines[0], scanlines_len);
```

**Comment by adamhooper** [comment]
Whew -- I wish I could replicate these problems. Oh well....

I've tried another fix: to change the build parameters. Could you please try v1.0.5 now? :)

**Comment by tommypreger** [comment]
No cigar... Now it seems like the very first issue reappeared? Hmm!

```
  CXX(target) Release/obj.target/lightnpng/src/init.o
In file included from ../src/init.cc:1:
../src/write_png.h:5:10: fatal error: 'tr1/cstdint' file not found
#include <tr1/cstdint>
         ^
```

**Comment by adamhooper** [comment]
Whew! I've set up Travis to compile on Mac OS X. Now I know it works.

Thank you for your patience! v1.0.6 has the solution.
